# PersistentVolumeClaim - 영구 스토리지 (AWS EBS 대체)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: microservices-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend2-storage
  namespace: microservices-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi

