apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend2
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-job
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-export-job
  namespace: microservices-demo


