# ResourceQuota - 리소스 제한 (AWS 리소스 제한 대체)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: microservices-demo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"

